
-- Total revenue
SELECT SUM(Total_spent)
FROM   cleaned_retail_stores_sales;

-- Total number of transactions
SELECT COUNT(Transaction_ID)
FROM   cleaned_retail_stores_sales;

--Total quantity sold
SELECT SUM(Quantity)
FROM   cleaned_retail_stores_sales;

--Average transaction value
SELECT AVG(Total_spent)
FROM   cleaned_retail_stores_sales
WHERE  Total_spent IS NOT NULL;

--Category generating the most revenue
SELECT   TOP 1 Category,
               SUM(Total_spent) AS total_revenue
FROM     cleaned_retail_stores_sales
GROUP BY Category
ORDER BY total_revenue DESC;

SELECT *
FROM   cleaned_retail_stores_sales;

--Top 10 individual items generating the most revenue
SELECT   TOP 10 Item,
                SUM(Total_spent) AS total_revenue
FROM     cleaned_retail_stores_sales
GROUP BY Item
ORDER BY total_revenue DESC;

--Location generating the most revenue
SELECT   Location,
         SUM(Total_spent) AS total_revenue
FROM     cleaned_retail_stores_sales
GROUP BY Location
ORDER BY total_revenue DESC;

--Most frequently payment method by customer
SELECT   Payment_method,
         COUNT(*) AS total_count
FROM     cleaned_retail_stores_sales
GROUP BY Payment_method
ORDER BY total_count DESC;

--Category generating the highest total quantity sold
SELECT TOP 1  Category,
               SUM(Quantity) AS total_quantity
FROM     cleaned_retail_stores_sales
GROUP BY Category
ORDER BY total_quantity DESC;

--Top 10 customers based on total amount spent
SELECT   TOP 10 Customer_ID,
                SUM(Total_spent) AS total_spent
FROM     cleaned_retail_stores_sales
GROUP BY Customer_ID
ORDER BY total_spent DESC;

--How does revenue change month by month, and which month generated the highest revenue? (Monthly revenue trend)

WITH     monthly_revenue
AS       (SELECT   month(Transaction_date) AS revenue_month,
                   year(Transaction_date) AS revenue_year,
                   sum(Total_spent) AS total_revenue
          FROM     cleaned_retail_stores_sales
          GROUP BY month(Transaction_date), year(Transaction_date))
SELECT   *,
         lag(total_revenue, 1) OVER (ORDER BY revenue_year, revenue_month) AS prev_month_revenue,
         round(100.0 * (total_revenue - lag(total_revenue, 1) OVER (ORDER BY revenue_year, revenue_month)) / NULLIF (lag(total_revenue, 1) OVER (ORDER BY revenue_year, revenue_month), 0), 2) AS mom_percent
FROM     monthly_revenue
ORDER BY revenue_year, revenue_month;

SELECT   TOP 1 month(Transaction_date) AS revenue_month,
               year(Transaction_date) AS revenue_year,
               sum(Total_spent) AS total_revenue
FROM     cleaned_retail_stores_sales
GROUP BY month(Transaction_date), year(Transaction_date)
ORDER BY total_revenue DESC;

--Which combination of product category and store location generates the highest revenue? (Category + location performance)
SELECT   TOP 1 Category,
               Location,
               sum(Total_spent) AS Total_revenue
FROM     cleaned_retail_stores_sales
GROUP BY Category, Location
ORDER BY Total_revenue DESC;

-- Do transactions marked as having a discount generate a different average transaction value compared with transactions without a discount? (Discount analysis)
SELECT   Discount_applied,
         count(*) AS Transaction_count,
         avg(Total_spent) AS average_transaction_value
FROM     cleaned_retail_stores_sales
GROUP BY Discount_applied
ORDER BY Discount_applied;

-- What is the average number of transactions and average amount spent per customer? (Customer purchasing behavior)
WITH   customer_summary
AS     (SELECT   Customer_ID,
                 count(*) AS Transaction_count,
                 sum(Total_spent) AS total_transaction_value
        FROM     cleaned_retail_stores_sales
        GROUP BY Customer_ID)
SELECT avg(CAST (Transaction_count AS DECIMAL (10, 2))) AS avg_no_of_transaction,
       avg(total_transaction_value) AS avg_transaction_value
FROM   customer_summary;

-- What percentage of total revenue is generated by the top 20% of customers? (Revenue concentration / Pareto analysis) 
WITH   customer_revenue
AS     (SELECT   Customer_ID,
                 SUM(Total_spent) AS Total_revenue
        FROM     cleaned_retail_stores_sales
        GROUP BY Customer_ID),
       ranked_customers
AS     (SELECT Customer_ID,
               Total_revenue,
               ROW_NUMBER() OVER (ORDER BY Total_revenue DESC) AS ranking,
               COUNT(*) OVER () AS total_customers,
               SUM(Total_revenue) OVER () AS overall_revenue
        FROM   customer_revenue)
SELECT SUM(Total_revenue) AS revenue_top_20,
       MAX(overall_revenue) AS revenue_total,
       CONCAT(ROUND(100.0 * SUM(Total_revenue) / NULLIF (MAX(overall_revenue), 0), 2), '%') AS top_20_revenue_percentage
FROM   ranked_customers
WHERE  ranking <= total_customers * 0.20;
